name = "ClimaParams"
uuid = "5c42b081-d73a-476f-9059-fd94b934656c"
authors = ["Climate Modeling Alliance"]
version = "0.10.6"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DocStringExtensions = "0.8, 0.9"
julia = "1"
TOML = "1"
Test = "1"
